name: "Lint Python code"
on:
  push: # Only execute pipeline when someone pushes a commit to these branches
    branches:
      - master
  pull_requests:
      - master

jobs:
  lint: # Name of the job
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.13"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix_os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python $ {{ matrix.python-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install ruff -r requirements.txt
      - name: Lint the project
        run: ruff check --output-format-github